-- Deprecated: the original single-row anonymous schema is not safe for customers.
-- Do not restore lsbarber_state or grant anon access to business tables.
-- Apply billing.sql and then commercial.sql. Neither deletes existing business rows.
